
CREATE TABLE HEARING_AID_FILTERS(
    ID           INTEGER NOT NULL  IDENTITY PRIMARY KEY
  , HEARING_AID_GUID                VARCHAR(36) NOT NULL default '5007A25D-8073-45C6-8B2B-A6A4E6C34C51'
  , HEARING_AID_NAME                VARCHAR(100) NOT NULL
  , MANUFACTURER                    VARCHAR(100) NOT NULL
  , DESCRIPTION                     VARCHAR(Max)
  , DESCRIPTION_PRODUCT_LINE        VARCHAR(100)
  , MAX_OUTPUT_DB_SPL               INTEGER
  , COCHLEAR_IMPLANT_COMPATIBLE     VARCHAR(100)
  , TINNITUS_MANAGEMENT_FEATURES    VARCHAR(100)
  , BATTERY_SIZE                    VARCHAR(100)
  , HEARING_AID_STYLE               VARCHAR(100)
  , MAX_GAIN_HEARING_LOSS_COMPATIBILITY VARCHAR(100)
  , STYLE_FORM_FACTOR               VARCHAR(100)
  , SOURCE_FILES_LOADED             INTEGER
  , SOURCE_FILES                    VARCHAR(2000)
  , CREATED_DATE                    DATETIME NOT NULL DEFAULT GETDATE()
  , CREATED_BY                      VARCHAR(100) NOT NULL DEFAULT 'Initial upload'
  , UPDATED_DATE                    DATETIME
  , UPDATED_BY                      VARCHAR(100)
);