
CREATE TABLE OTO_TBL_PATIENTS (
    PATIENT_ID INT IDENTITY(1,1) PRIMARY KEY,
    FULL_NAME NVARCHAR(100) NOT NULL,
    GENDER NVARCHAR(10) NOT NULL,
    AGE INT NOT NULL,
    ADDRESS NVARCHAR(255) NULL,
    PHONE NVARCHAR(20) NULL,
    EMAIL NVARCHAR(100) NULL,
    LAST_VISIT DATETIME2 NULL,
    CREATED_DATE DATETIME2 DEFAULT GETDATE(),
    MODIFIED_DATE DATETIME2 DEFAULT GETDATE(),
    
    ---- CONSTRAINTS
    --CONSTRAINT CHK_OTO_TBL_PATIENTS_AGE CHECK (AGE >= 0 AND AGE <= 150),
    --CONSTRAINT CHK_OTO_TBL_PATIENTS_GENDER CHECK (GENDER IN ('MALE', 'FEMALE', 'OTHER')),
    --CONSTRAINT UQ_OTO_TBL_PATIENTS_EMAIL UNIQUE (EMAIL)
);

-- ADD INDEXES FOR BETTER PERFORMANCE
CREATE INDEX IDX_OTO_TBL_PATIENTS_FULL_NAME ON OTO_TBL_PATIENTS(FULL_NAME);
CREATE INDEX IDX_OTO_TBL_PATIENTS_EMAIL ON OTO_TBL_PATIENTS(EMAIL);
CREATE INDEX IDX_OTO_TBL_PATIENTS_PHONE ON OTO_TBL_PATIENTS(PHONE);
CREATE INDEX IDX_OTO_TBL_PATIENTS_LAST_VISIT ON OTO_TBL_PATIENTS(LAST_VISIT);

-- ADD COMMENTS TO TABLE AND COLUMNS
EXEC sp_addextendedproperty 
    @name = N'MS_Description', 
    @value = N'OTOLOGY PATIENT MASTER TABLE - STORES ALL PATIENT INFORMATION',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'OTO_TBL_PATIENTS';

EXEC sp_addextendedproperty 
    @name = N'MS_Description', 
    @value = N'UNIQUE PATIENT IDENTIFIER - PRIMARY KEY',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'OTO_TBL_PATIENTS',
    @level2type = N'COLUMN', @level2name = 'PATIENT_ID';

-- INSERT SAMPLE DATA
INSERT INTO OTO_TBL_PATIENTS (FULL_NAME, GENDER, AGE, ADDRESS, PHONE, EMAIL, LAST_VISIT) VALUES
('JOHN SMITH', 'MALE', 45, '123 MAIN ST, NEW YORK, NY 10001', '+1-555-0123', 'JOHN.SMITH@EMAIL.COM', '2024-01-15 10:30:00'),
('EMILY DAVIS', 'FEMALE', 28, '456 OAK AVE, LOS ANGELES, CA 90210', '+1-555-0124', 'EMILY.DAVIS@EMAIL.COM', '2024-01-20 14:15:00'),
('MICHAEL JOHNSON', 'MALE', 62, '789 PINE RD, CHICAGO, IL 60601', '+1-555-0125', 'MICHAEL.JOHNSON@EMAIL.COM', '2024-01-10 09:45:00'),
('SARAH WILSON', 'FEMALE', 34, '321 ELM ST, HOUSTON, TX 77001', '+1-555-0126', 'SARAH.WILSON@EMAIL.COM', '2024-01-25 11:20:00'),
('DAVID BROWN', 'MALE', 51, '654 MAPLE DR, PHOENIX, AZ 85001', '+1-555-0127', 'DAVID.BROWN@EMAIL.COM', '2024-01-18 16:00:00');

