-- STORED PROCEDURE: GET PATIENT BY ID
CREATE PROCEDURE USP_OTO_GET_PATIENT_BY_ID
    @PATIENT_ID INT
AS
BEGIN
    SET NOCOUNT ON;
    
    SELECT 
        PATIENT_ID,
        FULL_NAME,
        GENDER,
        AGE,
        ADDRESS,
        PHONE,
        EMAIL,
        LAST_VISIT,
        CREATED_DATE,
        MODIFIED_DATE
    FROM OTO_TBL_PATIENTS
    WHERE PATIENT_ID = @PATIENT_ID;
END;
GO