-- STORED PROCEDURE: INSERT NEW PATIENT
CREATE PROCEDURE USP_OTO_INSERT_PATIENT
    @FULL_NAME NVARCHAR(100),
    @GENDER NVARCHAR(10),
    @AGE INT,
    @ADDRESS NVARCHAR(255) = NULL,
    @PHONE NVARCHAR(20) = NULL,
    @EMAIL NVARCHAR(100) = NULL,
    @LAST_VISIT DATETIME2 = NULL
AS
BEGIN
    SET NOCOUNT ON;
    
    INSERT INTO OTO_TBL_PATIENTS (
        FULL_NAME, 
        GENDER, 
        AGE, 
        ADDRESS, 
        PHONE, 
        EMAIL, 
        LAST_VISIT
    )
    VALUES (
        @FULL_NAME,
        @GENDER,
        @AGE,
        @ADDRESS,
        @PHONE,
        @EMAIL,
        @LAST_VISIT
    );
    
    -- RETURN THE NEW PATIENT ID
    SELECT SCOPE_IDENTITY() AS NEW_PATIENT_ID;
END;
GO