
-- STORED PROCEDURE: GET ALL PATIENTS
CREATE PROCEDURE USP_OTO_GET_ALL_PATIENTS
AS
BEGIN
    --SET NOCOUNT ON;
    
    SELECT 
        PATIENT_ID,
        FULL_NAME,
        GENDER,
        AGE,
        ADDRESS,
        PHONE,
        EMAIL,
        LAST_VISIT,
        CREATED_DATE,
        MODIFIED_DATE
    FROM OTO_TBL_PATIENTS
    ORDER BY DES PATIENT_ID;
END;