

-- STORED PROCEDURE: DELETE PATIENT
CREATE PROCEDURE USP_OTO_DELETE_PATIENT
    @PATIENT_ID INT
AS
BEGIN
    SET NOCOUNT ON;
    
    DELETE FROM OTO_TBL_PATIENTS
    WHERE PATIENT_ID = @PATIENT_ID;
    
    -- RETURN ROWS AFFECTED
    SELECT @@ROWCOUNT AS ROWS_AFFECTED;
END;
GO