-- STORED PROCEDURE: UPDATE PATIENT
CREATE PROCEDURE USP_OTO_UPDATE_PATIENT
    @PATIENT_ID INT,
    @FULL_NAME NVARCHAR(100),
    @GENDER NVARCHAR(10),
    @AGE INT,
    @ADDRESS NVARCHAR(255) = NULL,
    @PHONE NVARCHAR(20) = NULL,
    @EMAIL NVARCHAR(100) = NULL,
    @LAST_VISIT DATETIME2 = NULL
AS
BEGIN
    SET NOCOUNT ON;
    
    UPDATE OTO_TBL_PATIENTS
    SET 
        FULL_NAME = @FULL_NAME,
        GENDER = @GENDER,
        AGE = @AGE,
        ADDRESS = @ADDRESS,
        PHONE = @PHONE,
        EMAIL = @EMAIL,
        LAST_VISIT = @LAST_VISIT,
        MODIFIED_DATE = GETDATE()
    WHERE PATIENT_ID = @PATIENT_ID;
    
    -- RETURN ROWS AFFECTED
    SELECT @@ROWCOUNT AS ROWS_AFFECTED;
END;
GO
